spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  session:
    store-type: none
yxdtyut:
  security:
    browser:
      loginUrl: /demo-signIn.html
      loginType: REDIRECT
#security:
#  basic:
#    enabled: false