spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  session:
    store-type: none
#yxdtyut:
#  security:
#    validate:
#      image:
#        width: 100
#        length: 6
#        urls: /user/*
#    browser:
#      loginUrl: /demo-signIn.html
#      loginType: REDIRECT
#security:
#  basic:
#    enabled: false