spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  session:
    store-type: none
security:
  basic:
    enabled: false
